opengapps/opengapps

CNAME

Change domain to opengapps.cf

---

scripts/inc.compatibility.sh

Add Double Quote

---

add_sourceapp.sh

Update add_sourceapp.sh for incorrect end of case sections

Update add_sourceapp.sh for incorrect end of case sections

---

scripts/inc.updatebinary.sh

Fixes issue #68 for device-specific config files.

Perdeviceconfig

---

README.md
upload_sources.sh

Creates upload_sources.sh which allows packagers to more easily generate 'clean' commits for each package. Fixes issue #73

Uploadscript

---

upload_sources.sh

Git is also required by the script

---

scripts/inc.aromadata.sh
scripts/inc.buildhelper.sh
scripts/inc.compatibility.sh
scripts/inc.installdata.sh
scripts/inc.updatebinary.sh

Refactor the lib generation code
Closes issue #82

Make WebView's libraries systemwide

---

scripts/inc.aromadata.sh

For issue #132 
- Add new Super apps
- Make title in installer match the Play Store name
- Avoid duplicate text from description and title.
- Add Swype Libs optional feature
- Change XDA link to homepage as it's home to that and more.
@mfonville @raulx222 Do I have it right? Don't have a device to test but it should work.

[AROMA] Update for Super and Various Cleanup

---

scripts/inc.aromadata.sh

@mfonville forgot to update the other part (that actually does the stuff) with the fixed typo.

[AROMA] Fix another Fi Typo

---

scripts/inc.aromadata.sh

[AROMA] Add Hindi Input

---

scripts/inc.aromadata.sh

[AROMA] Fix Zhuyin

---

scripts/inc.aromadata.sh

- Change Hindi to Indic for #157 
- Remove lots of duplicate text
- Changed some wordings
- Remove Lots of Blank Space
- Remove comments left over from the AROMA Demo
- Combined UI, Font, and Splash sections into one.
@mfonville @raulx222 This might need double checking to make sure any important stuff didn't accidentally get deleted.

[AROMA] Massive Cleanup

---

scripts/inc.aromadata.sh
scripts/inc.buildhelper.sh
scripts/inc.compatibility.sh
scripts/inc.updatebinary.sh

Fixes issue #169 and makes swypelibs installed by default again, but less invasive

Swypelibsrevised

---

scripts/build_gapps.sh
scripts/inc.buildtarget.sh
scripts/inc.compatibility.sh
scripts/inc.installdata.sh
scripts/inc.updatebinary.sh

Do not remove Google App if no AOSP app available; fixes issue #166

Preventgoogleremovals

---

scripts/inc.updatebinary.sh

Skip removal of recovery.log in /tmp/

---

scripts/inc.compatibility.sh
scripts/inc.updatebinary.sh

- Fix skipswypelibs by fixing minor logic bug in f429c999999509236aa6dcdd1ef2263d0fbeaa33
- Add related UI prints and logging
- Improve existing UI prints and logging in lines surrounding affected code

Fix skipswypelibs and add related UI prints and logging

---

scripts/inc.buildhelper.sh
scripts/inc.buildtarget.sh
scripts/inc.compatibility.sh
scripts/inc.installdata.sh
scripts/inc.updatebinary.sh

Fixes #208 and is inspired on #234

GoogleCamera Legacy fallback for non-Nexus

---

report_sources.sh

(including dashes :) ) and for report this time!

Update "Application Name" width to 46 from 45

---

README.md

Correct opengapps.org params for architectures.

---

scripts/inc.installer.sh

Fixes nothing.
Changes:
- remove YuBrowser in Mokee ROM

remove YuBrowser in Mokee ROM

---

scripts/inc.installer.sh

Fixes nothing.
Changes:
- Add FlymeOS Browser to browser removal list
- Add FlymeOS Email to email removial list
- Add FlymeOS Keyboard to keyboard removal list
@opengapps/developers , @mfonville

Add more FlymeOS apps to removial list

---

README.md

Changes:
- Removes redundant 'be' in README
-
-

README : Fix grammar

---

scripts/bkup_tail.sh

Changes:
- Removed redundant pittpatt
My knowledge of scripts isn't that big, but I guess this was redundant?

Removed redundant file path pittpatt

---

scripts/inc.installer.sh

Fixes nothing.
Changes:
-Add MIUI apps
@opengapps/developers, @mfonville

Add MIUI apps

---

add_sourceapp.sh

Fixes nothing.
Changes:
-Update APK-Tool framework to apktool_2.1.1.jar
@opengapps/developers, @mfonville

Update APK-Tool framework

---

.github/ISSUE_TEMPLATE.md

@mfonville, this is the change I discussed over hangouts.

Minor updates to ISSUE_TEMPLATE

---

README.md

Update alt text for donate button

---

scripts/inc.installer.sh

Fixes #.
Changes #.
@opengapps/developers, @mfonville

Add Mz keywords

---

scripts/inc.installer.sh

Fixes #.
Changes:
-
-
-
@opengapps/developers, @mfonville 
Signed-off-by: alexlartsev19 <alexlartsev19@gmail.com>

Add missed keywords

---

upload_sources.sh

Look for up/downgrades when commiting

---

add_sourceapp.sh

Changes:
- Do not block downgrades

Additional changes for up/downgrade of API levels

---

report_sources.sh
scripts/inc.buildhelper.sh

Fixes Column Widths for ApplicationName and VersionName.

Fixed column widths

---

upload_sources.sh

Ignore vrmode for playstore

---

upload_sources.sh

Ignore vrmode for com.google.vr.vrcore as well

---

scripts/inc.sourceshelper.sh

Igmore vrmode for com.google.vr.vrcore (2)

---

scripts/inc.sourceshelper.sh
upload_sources.sh

Change vrmode flagging to whitelist since only photos has both right now

---

scripts/inc.sourceshelper.sh
upload_sources.sh

Add Google Play Videos to vrmode whitelist

---

upload_sources.sh

Since the '-q' kept the variable empty...

Moved logic into if statement

---

scripts/inc.installer.sh

Fixes #355
Changes:
- Remove ch_con_recursive function
- Don't recursively set context in /system/*

Run ch_con on every copied file

---

scripts/inc.installer.sh

Fixes #411 
Changes:
- add LineageOS check

add LineageOS support

---

scripts/inc.installer.sh

Change build.prop error receiver entry to gms (#407)

---

upload_sources.sh

Artem requested non-default user-agents: https://github.com/opengapps/apkcrawler/issues/62

Add user-agent to upload script per APKMirror's request

---

scripts/inc.installer.sh

Commit de6bcc79469cbfb909b8a2211601a86156799a8d made this safe.

Add CMBugReport to optional remove list

---

scripts/inc.aromadata.sh

New keywords in the remove list: CMBugReport, LRecorder, SoundRecorder
New keyword in the extra list: GoogleAssistant

Add new keywords to AROMA

---

scripts/bkup_tail.sh

Fixed typo causing execution of arthmatic opperation

---

scripts/inc.sourceshelper.sh
upload_sources.sh

Added Calculator to .watch list per APKMirror's list

---

scripts/inc.installer.sh

Add LineageOS Br0Zip to optional remove list

---

scripts/inc.installer.sh

Changes:
- Added PABrowser, SnapdragonGallery, SnapdragonMusic

Add apps from PA 7.1.x

---

scripts/inc.installer.sh

https://review.lineageos.org/#/c/182429/
Fixes #525 
Changes:
-added new line: priv-app/Eleven

Add privileged music app (Eleven) to the list

---

upload_sources.sh

https://plus.google.com/+apkmirror/posts/T5Tg8Y8vYdG

Move APKMirror uploader to HTTPS:

---

scripts/inc.installer.sh

Add keyword for LineageOS Updater

---

scripts/inc.aromadata.sh

Drop deprecated news widget app from Aroma installer

---

scripts/inc.buildtarget.sh

Fixes https://github.com/opengapps/opengapps/issues/691

Fall back to camera.experimental2016 xml and jar again

---

scripts/inc.installer.sh

Fix tmp directory typo

---

scripts/inc.installer.sh

Check for Pixel 3 device names in install script

---

README.md

- Linter fixes
- Use the SourceForge links

Sourceforge update

---

scripts/inc.installer.sh

Unlike TWRP Lineage Recovery mounts system_root in /system_root ( as expected by Android )

Fix SAR on Lineage Recovery

---

scripts/inc.compatibility.sh

This fixes the build issues after the Q merge.

Rename build target for Platform Services

---

scripts/inc.installer.sh

- fix case where TWRP has /system_root mountpoint but ROM is non-SAR
- fix regression in ui_print when final character is \
- adjust section spacing for uniformity, and clean up one last trailing ;
- fix the following bugs and/or stderr in the log:
```
grep: /system/product/etc/: No such file or directory
ash: bad number
find: /system/product/app: No such file or directory
find: /system/product/priv-app: No such file or directory
find: /system/product/app: No such file or directory
find: /system/product/priv-app: No such file or directory
find: /system/vendor/pittpatt: No such file or directory
find: -exec requires an argument
```

installer: mount and output fixes, touch ups

---

scripts/inc.packagetarget.sh

Changes:
- Use all threads for xz compression.
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

speedup xz compression by using all available threads

---

scripts/bkup_tail.sh

- the recovery.log stderr after current addon.d:
find: /system/vendor/pittpatt: No such file or directory
sh: bad number
sh: bad number
sh: bad number
...
(repeated for every entry in $list_files)
- hide stderr from find as in the installer
- $API is never set outside of build time, so use ro.addon.sdk from g.prop as $rom_build_sdk to mirror the same fix in the installer
- build.prop perm fix was looping needlessly
- clean up remaining ;

addon.d: fix stderr and permission fixing behavior

---

scripts/inc.compatibility.sh

See https://github.com/opengapps/opengapps/pull/821 for context.
Signed-off-by: Ilya Danilkin <nezorflame@gmail.com>

Move SoundPicker to Nano variant

---

scripts/templates/installer.sh

Signed-off-by: Jesse Chan <jc@lineageos.org>

installer: properly support dynamic partitions

---

scripts/templates/installer.sh

Somehow pull request #838 caused the submodules in `sources/` to change. I'm not sure how that happened, or why `git show` and `git diff` don't show anything. This pull request contains two commits: the first reverts the commit that caused the submodule change, and the second re-does the commit but without the submodule change.
cc @nezorflame @razorloves @mfonville

Fix accidental submodule change

---

scripts/inc.aromadata.sh
scripts/templates/installer.sh

Fixes #855 and #856 properly.
Changes:
- Remove preodex paths as it contains errors, is not used and will not work on new devices.

Remove preodex code paths.

---

scripts/templates/installer.sh

- No need for extra functions
- No need to echo | grep, when we can just case

installer: simplify ch_con* usage

---

upload_sources.sh

Fixes #.
Changes:
Add Wear OS App Info
-
-

add wear os app info

---

scripts/inc.buildtarget.sh

Changes:
- Removes webviewgoogle from the tvstock list

Remove Google Webview from tvstock

---

scripts/inc.buildtarget.sh

Adds back mistakenly removed package and removes now useless package.

ATV Updates

---

scripts/templates/installer.sh

- fix /system/bin/* execution on recoveries using LD_CONFIG_FILE
- add additional BOOTCLASSPATH entry for /apex mounts
- try to preserve a working /etc/fstab on AOSP Q-based recovery and newer
- fix sloppy/unpredictable `cmd && this || that` statements by being a bit more POSIX to avoid any potential issues when stdout/err are redirected
- do apex mounts before /system bind to always ensure a working underlying shell environment
- improve support for mounting dynamic/logical partitions from /dev/block/mapper
- don't rely on props if possible: determine dynamic/logical partitions from /dev/block/mapper presence, and detect slots more robustly using props and cmdline
- clean up all use of test
Closes #902

installer: mounting script updates and function logic fixes

---

scripts/inc.buildtarget.sh

Fixes #742 
Based upon user feedback.
Accompanied by this PR in the sources: https://gitlab.opengapps.org/opengapps/all/-/merge_requests/49

Fix gearheadstub by moving it to priv-app

---

scripts/bkup_tail.sh
scripts/templates/installer.sh

Changes:
- Added support for /system_ext partition (mount and search apps for deletion)

Update partitions used by installer and backup scripts

---

scripts/templates/installer.sh

This adds the newest pixels. 4a 5g / 5 / 5a

Update pixel device list

---

scripts/inc.buildtarget.sh

Fixes many apps failing to detect play store support.

Add atv overlay for api 30+

---

scripts/inc.buildtarget.sh

Change in Android 12 and/or 12L.
_Not sure if this is required for Android 12._
`SYSTEM_AUTOMOTIVE_PROJECTION` - [android.googlesource.com](https://android.googlesource.com/platform/frameworks/base/+/8240dbd571cb86b04ed0fe252eeb381971b7a54d^!/)
First time I made an overlay. :upside_down_face:
Not sure if I set `android:priority` correctly.
_Got a little confused reading about setting it._
My WIP overlay - [GitLab](https://gitlab.opengapps.org/ip/all/-/commit/69c2bfdb938577eb842fbb82a3b9760ea270827d)
Cheers all. :cowboy_hat_face:

Android Auto
