opengapps/opengapps

report_sources.sh, scripts/inc.buildhelper.sh, scripts/inc.installdata.sh
**UNTESTED**
Please test and review, I have not tested these changes.
echo -n is implementation-defined and therefor not portable
Never use echo flags unless your script specifies a specific shell to be used (e.g. #!/bin/bash) to ensure consistent flag behavior. Please see this page for more information: [pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html](pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html). Specifically [OPERANDS](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html#tag_20_37_05), [APPLICATION USAGE](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html#tag_20_37_16) and [RATIONALE](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html#tag_20_37_18).
Partially fixes issue #48
=> Replace echo -n usage with printf

scripts/inc.packagetarget.sh
\t was being output literally and would not have aligned the columns anyway. Use printf to properly align the columns.  
Before: [http://hastebin.com/ametusogor.txt](http://hastebin.com/ametusogor.txt)
After: [http://hastebin.com/imogebuwip.txt](http://hastebin.com/imogebuwip.txt)  
The printf relies on googleonetimeinitializer and 400-480-560-640 being the largest strings in their columns. It's not worth complicating things by adding width detection for the columns just for cosmetics.  
If you're not happy with using hardcoded values, we can always switch to plain printf with unaligned tabs or echo with spaces since it will be unaligned anyway.  
Partially fixes issue #48
=> Fix and properly align app_sizes.txt

scripts/inc.installdata.sh
This will be great for the `fornexus` package as it works on stock Moto devices that have these built-in.
@rapperskull @mfonville
=> Remove Moto Camera/Gallery when installing Google variants

scripts/inc.compatibility.sh, scripts/inc.updatebinary.sh
For example gapps-config can now contain:
"skipkeybdlib" to avoid upgrade of stock keyboard lib (can be used as workaround for recent CyanogenMod keyboard issues)
"forceclean" to enforce clean install
=> Support forceclean and skipkeybdlib tokens in gapps-config and tweak keyboard treatment

scripts/inc.updatebinary.sh
Thanks for this great project.
This PR fix installation hangs at [Line 573](https://github.com/opengapps/opengapps/blob/b320e48704e344f5f74f3cfeda6943807b158037/scripts/inc.updatebinary.sh#L573) when flashing with FlashFire and gapps-config not exists.
I have noticed only TWRP is supported in the FAQ, but there are several devices that custom recovery isn't available, unless unlock the bootloader (and unlocking may cause some feature stop working, such as Galaxy S6), so I hope an on-device flasher can also be basically supported.
=> Fix installation hangs when flashing with FlashFire.

scripts/inc.installdata.sh
Removes prebuilt Chromium which ships with custom ROMs that decided the AOSP Browser was bad
=> Add Chromium to browser removal list

scripts/inc.aromadata.sh, scripts/inc.buildtarget.sh, scripts/inc.compatibility.sh, scripts/inc.updatebinary.sh
Last relevant commits moved PackageInstaller into core GApps, making it impossible to exclude with a .gapps-config keyword or AROMA.
In the meantime, the open gapps GooglePackageInstaller is buggy: http://i.imgur.com/lhAZnBd.png (Stock nexus rom's PackageInstaller doesn't do that) (DPI bug?)
This commit:
- Moves PackageInstallerGoogle from core to Stock package
- Makes it configurable with tag "PackageInstallerGoogle"
- Adds it as an option in the AROMA version (untested by me, followed previous commits' structure)
- RESULT: http://i.imgur.com/HEcUlWY.png with a Open-GApps STOCK package
=> PackageInstaller: move into PicoGApps, making it removable

scripts/inc.installer.sh
Fixes private issue.
Changes:
- Made the installer remove the PA browser automatically.
@mfonville (because it looks like @opengapps/developers isn't really doing the thing it should be doing?)
=> Add PA Browser to browser removal list

scripts/inc.installer.sh
Fixes #299.
@opengapps/developers @mfonville
Some recoveries (e.g. CyanogenMod recovery) run strict SELinux policies
that disallow creating symlinks and hardlinks in /tmp and setting
permissive mode. In such case install BusyBox applets as shell script
wrappers instead of symlinking them.
=> Fallback to script wrappers if symlinking failed when installing busybox

scripts/inc.installer.sh
Changes:
- Whitelists bacon
@opengapps/developers Works like a charm. No crashes or anything. However, I was only able to flash it over CM13 stock apps with clean install (i.e. wipe data)
=> Whitelist OnePlus One (bacon) for Google Dialer

scripts/inc.installer.sh
Fixes dialer not installing an A0001 variant of Oneplus One (We still have to set it default in the settings right?).
Changes:
- Adds A0001 to the whitelist
The A0001 variant also is copatible with GoogleDialer
=> Added A0001 variant for Oneplus One

add_sourceapp.sh, get_speechfiles.sh, report_sources.sh, scripts/build_gapps.sh, scripts/inc.buildhelper.sh, upload_sources.sh
NEEDS TESTING AND REVIEW
This PR is completely untested and blind, though the changes should be relatively safe.
Changes:
- Added ShellCheck directives to find sourced files
- Blind fixes to silence a few ShellCheck warnings
- 85ce8a9 assumes you meant to treat the variables as strings (looks right since sed and cut are used)
- 7cf01a5 $f doesn't exist AFAIK. Appears $file was meant to be used
I used shellcheck source=scripts/* in scripts/build_gapps.sh so recursively running ShellCheck from the projects root directory works. ShellCheck doesn't appear to offer a nice way of handling this. Let me know if you want it changed.
I'll post a new ShellCheck log in issue #48 for developers that are familiar with the code.
=> ShellCheck fixes

upload_sources.sh
=> Use APKMirror's MD5 pre-check for duplicates

scripts/inc.installer.sh
Per my conversation with @mfonville we can expand the LOS CMSetupWizard removal to CM14+.
Also I noticed Recorder popped up in the latest LOS14 weekly, so handle that while we're at it. 😃
=> Expand LOS14+ CMSetupWizard removal to CM14+  & add Recorder removal support

scripts/inc.installer.sh
Fix per discussion with @szhu starting here: https://github.com/opengapps/opengapps/issues/391#issuecomment-269862019
Previously subsequent 'dirty' GApps flashes would remove paths which would still be relevant after a ROM update since the target files were removed during the initial post-ROM flash
=> Make User App Removals persistent

scripts/bkup_tail.sh
@osm0sis suggested that older toybox versions might not handle `sed -e` correctly, causing garbage to be assigned to free_tmp_size_kb. We can rely on a shell's native field splitting to "squeeze" the spaces between columns in `df -k`. Simply omit the quotes around $(df ...).
I've tested this in `mksh` and `busybox sh`.
=> addons.d: Simplify free /tmp space variable creation

scripts/inc.installer.sh
Few ROMs that are based on CAF, use CAF's version of Snap (i.e. SnapdragonCamera). The script thus fails to replace SnapdragonCamera with GoogleCamera.
References:
https://source.codeaurora.org/quic/la/platform/packages/apps/SnapdragonCamera/
=> installer.sh: Add SnapdragonCamera to removal list

scripts/inc.installer.sh
based on https://github.com/LineageOS/android_vendor_cm/commit/7674e0521af98548bec9ac85c084ce4340329c1c
@mfonville , merge this change, if stock LineageOS SetupWizard will be crash on LOS builds after 2016.02.16. If not - close pull request
=> inc.installer.sh: Add LineageSetupWizard

scripts/inc.installer.sh
The install_extracted method may be used to copy files inside target directories which are symlinks, and not actual folders, like in the case of libs in /vendor/lib* in devices with separate /vendor partition, like the Nexus 5X and the Nexus 6P.
However, the recursive option of cp can't handle it, as it is already documented as a linux bug here:
https://lists.freebsd.org/pipermail/freebsd-bugs/2013-February/051809.html
which produces the below output in recovery.log:
```
extracting: /tmp/GApps/faceunlock-lib-arm64.tar.lz  
Found GApps/faceunlock-lib-arm64 DPI path: unknown
cp: target '/system/./vendor' is not a directory
```
This important bug was somewhat "hidden" as the only file that Open-GApps currently try to copy into /vendor/lib* is libfrsdk.so, required only for a working Facelock …
=> install_extracted: fix bug in copying into symlinked folders

scripts/inc.installer.sh
* If a prop exists more than once in a file that's parsed
for it, only return the first instance. Otherwise you end
up with another, line-breaked, instance of said prop, which
doesn't tend to play nicely with scripts that are expecting
a single value.
Fixes #.
Changes:
-
-
-
=> installer: only take the first instance of a prop

scripts/inc.installer.sh
Looks like there was an omniswitch_list created  but it was never added to the optional_aosp_remove_list.
=> Added omniswitch to the optional_aosp_remove_list

scripts/inc.installer.sh
This will be a popular location for ROMs to place
gapps-config files in.
=> installer: Check /tmp/install for gapps-config

scripts/inc.installer.sh
OpenGapps will be able to remove OnePlus Dialer (OxygenOS) to avoid conflicts with Google Dialer.
=> installer.sh: add oneplus dialer to removal list

scripts/inc.buildtarget.sh, scripts/inc.compatibility.sh, scripts/inc.installer.sh, scripts/inc.sourceshelper.sh
HotwordDetection now relies on device-specific soundtrigger and
audio_platform mappings. The proprietary APK HotwordDetection should be included with devices pulled from stock firmware dumps. 
Signed-off-by: Jacob Whatley <jacob.whatley91@gmail.com>
Fixes #409 
Changes:
- #460
=> scripts: remove HotwordDetection

scripts/inc.buildtarget.sh
Changes:
- Removes the BT pairing apps that are specific to fugu
GamepadPairingService specifically causes a problem on Lineage because it requests a shared id with the main Bluetooth app. That causes a signature check error because gamepad is signed with googles key and Bluetooth is signed with test or lineage keys. End result is no bluetooth at all.
Since these are fugu specific, I'd like to see them removed from the general tvstock package. Aosp pairing works fine on the Shield Android TV.
=> Remove fugu specific pairing apps

add_sourceapp.sh
- Android O Final Dev Preview support (https://github.com/iBotPeaches/Apktool/issues/1520)
- SnakeYAML 1.1.8 Android Support (https://github.com/iBotPeaches/Apktool/issues/591)
- Fix issue with APKs taking longer than usual to parse resources (https://github.com/iBotPeaches/Apktool/issues/1489)
- Fix issue with internal binaries not accessible in a Spring boot environment. (https://github.com/iBotPeaches/Apktool/issues/1543)
- Fix issues with rebuilding applications originally built with aapt2. (https://github.com/iBotPeaches/Apktool/issues/1520)
- Patch aapt to support the $ character in resource filenames. (https://github.com/iBotPeaches/Apktool/issues/1532)
- Fix issue where apktool was holding locks onto files during execution. (https://github.com/iBotPeaches/Apktool/pull/1561)
- Fix …
=> Update APKtool to 2.2.4

scripts/build_gapps.sh
`AndroidPlatformServices` doesn't get added to 8.0+ builds, as `api26hack` (added in a93b82d97e2693e333aac751f906165249739298) isn't actually called.
=> build_gapps.sh: Call api26hack

scripts/inc.buildtarget.sh
This prevents any ROM customization from affecting leanback. This
should be a ROM level customization, not gapps.
=> Remove AtvCusomization

scripts/inc.buildtarget.sh
SetupWraith requires read and write gsettings permissions which
are only allowed to platform signed apps. Otherwise the wizard will
crash at the end of the loop before marking the device provisioned,
which causes a plethora of issues. So, ROMs need to ship ship
SetupWraith directly, signing it with their platform key.
Lineage is already making changes to work with this issue. But all ROMs will have this same problem if SetupWraith isn't platform signed. Ciwrl compared keys on stock Fugu and found that SetupWraith is platform signed there, and that it's only gapp that is.
=> Remove setupwraith from tvstock

scripts/inc.aromadata.sh, scripts/inc.buildtarget.sh, scripts/inc.compatibility.sh
-Added Carrier Services (com.google.android.ims) to `gappssuper`. Keyword `carrierservices`. This app is found inside of the 8.1 image for the Pixel 2 under `/system/priv-app/CarrierServices`
-Restricted AndroidPlatformServices (com.google.android.gms.policy_sidecar_o) to only API26, as that app is found only in an 8.0 image for the Pixel 2
-PackageInstallerGoogle will **only** install on API23, API26, and API27. If API24 or API25 is targeted for builds, PackageInstallerGoogle is skipped
-It has been reported that dialer_experience.xml is serving no purpose as of now. Remove it from being included in builds (See https://github.com/opengapps/opengapps/pull/580#issuecomment-369463327 by @elmkzgirxp)
=> Bundle Carrier Services, Restrict PlatformServices, PackageInstallerGoogle only for API23/26/27, Remove useless dialer_experience.xml

scripts/inc.buildtarget.sh
- Found in /system/etc/sysconfig, this file is no longer in builds for Oreo
=> Include dialer_experience.xml in builds for Nougat and below

scripts/inc.buildtarget.sh
This is needed to not have "not supported" message warning pop up in Google Dialer, on a device that is not a Pixel or a Nexus, even on Android Oreo.
=> Bring back etc/sysconfig/dialer_experience.xml for all

scripts/inc.compatibility.sh
Using it in this situation causes cameragooglelegacy-arm, cameragooglelegacy-common, dialergoogle, and pixellauncher to be ignored when building for API23 and API26+, while attempting to bring compatibility with PackageManagerGoogle installation for those APIs. All other APIs build the above mentioned packages fine.
=> Don't use elif statement for separation

scripts/inc.aromadata.sh, scripts/inc.installer.sh
For now, the restriction is lifted for Lineage 15.1, as I cannot verify if PackageInstallerGoogle will also work with LineageOS 15.0.
=> Allow PackageInstallerGoogle installation on LineageOS 15.1

scripts/inc.aromadata.sh, scripts/inc.installer.sh
This includes:
- Rearranged entries to match the ordering and options given in the wiki: https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options
- Adding new selections that were never present before
Other fixes:
- Add "logcat" keyword to "Optional Stock/AOSP/ROM Removal List"
=> Update the aroma installer to be inline with the wiki and other fixes

scripts/inc.buildtarget.sh
Initially reported here, `Could not find tag for key 'com.google.nexus.experimental2017.request.disable _hdrplus` is an issue relating to `com.google.android.camera.experimental2017.xml` and `com.google.android.camera.experimental2017.jar`
https://forum.xda-developers.com/showpost.php?p=75752131&postcount=5158
For now, continued use of the 2016 versions solves the FC'ing problem, until we know what is wrong/different with the 2017 versions.
Confirmations on Nexus 5X and Nexus 6P:
https://forum.xda-developers.com/showpost.php?p=75762279&postcount=5178
https://forum.xda-developers.com/showpost.php?p=75763026&postcount=5179
As for `pixel_2017.xml`, it was thought to enable wallpaper category exclusive to the Pixel 2: "Keep Looking", not "Come Alive" and "Come and Play", as those are already …
=> Fall back to camera.experimental2016.xml and camera.experimental2016.jar, and remove unknown purpose "pixel_2017.xml" permission

scripts/inc.compatibility.sh
The logic from #586 was faulty and caused dialergoogle, pixellauncher, and cameragooglelegacy to be ignored on Nougat. This should fix the logic.
=> Fix faulty logic from #586

scripts/inc.buildtarget.sh, scripts/inc.compatibility.sh, scripts/inc.sourceshelper.sh
First commit updates the scripts to use the new tvlauncher for api 26+.
Second commit fixes tvstock using the incorrect music app.
Third commit adds back setupwraith for api 26+. This has been tested against Lineage 15.1. It's possible the apk from fugu 8.0 also fixes the issues on api <=25, but this has not been tested, so this commit only adds it in for newer apis.
Fourth commit removes a few more ATV apps. These error out on mismatched shared user sigs, making them unusable unless platform signed.
Fugu is now having space issues. I'll follow up later with a PR to add a tvmini variant. This is mainly to get arm64 builds in shape for foster (nvidia shield android tv).
=> O ATV Updates

scripts/inc.installer.sh
Add CypherOS (AOSCP) apps to optional removal list:
- Bolt
- CameraX
- GalleryX
- MusicX
=> inc.installer.sh: add CypherOS apps to optional removal list

scripts/inc.aromadata.sh, scripts/inc.buildtarget.sh, scripts/inc.installer.sh
Allow using the +DialerStock option to keep the AOSP Dialer in stock/super/aroma.
=> Add option to keep the AOSP Dialer when Google Dialer is installed.

scripts/inc.installer.sh
Looks like this was missing, `StorageManagerStock` is currently a no-op.
=> Add storagemanagerstock to AOSP remove list

scripts/inc.buildtarget.sh, scripts/inc.compatibility.sh, scripts/inc.installer.sh
**Scripts: Remove Data Transfer Tool from gappscore**
Using a non-Pixel SetupWizard, we do not need to have this included in installation. The new SetupWizard will not force itself to download the tool either, and usually ending up being stuck in setup after. Notifications (such as the download notification) will also work properly now, instead of having to disable the tool after setup.
- Moved `datatransfertool` from "`core`" to "`gapps`", and only removed the keyword, in case that app is needed for something else.
- I have included screenshots of the alternative SetupWizard [in an album here](https://imgur.com/a/QT2S0kA), which shows all of the screens a user goes through.
- In the Android Settings menu, there is no trace of the "Pixel" string, for example "Finish setting up your Pixel …
=> Removal of Pixel's Setup Wizard in favor of "Universal" variants

scripts/inc.aromadata.sh, scripts/inc.buildtarget.sh, scripts/inc.compatibility.sh, scripts/inc.installer.sh
**Add Stock WallpaperPicker (wallpapersstock) to optional remove list**
- Installing Google Wallpapers will automatically remove stock WallpaperPicker
- Stock WallpaperPicker can be removed by adding keyword "wallpapersstock" to gapps-config or selected in Aroma
- Clarify entries of "wallpaper" in Aroma as "Google Wallpapers"
**Bring up OpenGApps to be more aligned with the default apps on Pixel devices**
The last update of default apps (for example: Stock) were aligned with the Google Nexus 5/6.
Now they are more inline with the Google Pixel generation (with the combination of Pixel 3's set of default apps in mind).
- Aroma: Added Android Auto as an option
- Aroma: Added Google Markup as an option
- Aroma: Added Digital Wellbeing as an option
- Aroma: Added Android minimum requirements …
=> Bring up OpenGApps to be more aligned with the default apps on Pixel devices

scripts/inc.installer.sh
* treble ROM builds move a lot of properties to /vendor/build.prop for compatibility with GSI's
* without this change, OpenGapps would fail to get the values of certain props such as DPI or camera API version (which would tell OpenGapps that Google Camera version = Legacy)
=> inc.installer.sh: getprop from vendor as well

scripts/inc.buildtarget.sh
Changes:
- Add missing permission files for atv
Mainly to get cast receiver working again, but probably fixes a lot of other, more subtle stuff too.
Edit: Needs opengapps/all/#40.
=> Add missing permission files for atv

scripts/inc.aromadata.sh, scripts/inc.buildtarget.sh, scripts/inc.compatibility.sh, scripts/inc.installer.sh
**Scripts: Extend Google Markup to ARM devices**
We now have an ARM variant of the library needed for Markup to work on more than just ARM64 devices. The origin of this library is from Pixel Experience [here](https://github.com/PixelExperience/vendor_pixelstyle/tree/pie/lib). Multiple testers in the unofficial OpenGApps Telegram group have confirmed with me that Markup now works perfectly. Unfortunately, I could not find an ARM factory image for Pie to source it from.
**Installer: Add support for locating gapps-config on the root of /sdcard**
In addition to the original location of finding a gapps-config file in `/sdcard/Open-GApps/`, let's also search the root of `/sdcard` for a gapps-config too.
**Prevent stock AOSP Dialer (Phone) from being removed**
Remove the entry for …
=> Allow Markup on ARM, Search more locations for gapps-config, prevent stock AOSP Dialer from being removed by default

scripts/inc.installer.sh
* When backuptool.sh is ran during ROM updates
it sets S variable to "/system/system", so we can
use it instead of hardcoding "/system". That way
proper permissions are restored properly.
=> Unbreak system-as-root A-only support

scripts/inc.installer.sh
Fixes #709.
Actually system-as-root A-only devices use "/system_root/system" for system. Current script can't handle it and it causes "Insufficient storage space available" error in installation.
=> Fix installation on system-as-root A-only devices

scripts/inc.installer.sh
* Checking /proc/mounts will work only if /system_root is mounted in that exact moment, while this will work unconditionally in TWRP
=> inc.installer: Properly check for A-only system-as-root devices

scripts/inc.compatibility.sh
All Google Chrome updates are done within api-21 branch,
api-24 branch has not been updated since months.
Fixes all recent OpenGapps packages for api >= 24 are shipped
with an outdated Google Chrome version - 72.0.3626.121 instead
of more recent 75.0.xxxx.yyy (75.0.3770.101 as of now).
Fixes https://github.com/opengapps/opengapps/issues/750
=> minapihack: use api-21 as min api for Google Chrome

scripts/inc.buildtarget.sh, scripts/inc.compatibility.sh
Tied to https://gitlab.opengapps.org/opengapps/all/merge_requests/2
This updates a few things about the atv package for api 28 is handled.
* The permission/priv-app/hiddenapi xmls have been rearranged a bit. This fixes privapp enforcing which is now enforced on lineage 16.0, and should not affect non-enforcing versions and roms.
* Several packages were removed in gapps for api 28. I didn't have a good way to handle this, so please review how I handled this in the last commit. I'm also uncertain how remove packages will handle this. These packages need deleted on update from an older build. I don't think this will be handled correctly.
=> Android P ATV Updates

scripts/inc.installer.sh
When using adb sideload, log files are not saved.
(/sideload is RO)
If you use a gapps-config file, the logs will be saved in the same directory as the config file.
If you do not use a config file, then the log files are copied to /sideload and disappear.
For now, copying the logs to /sdcard when /sideload is detected seems to work.
=> Copy logs to sdcard/ when using sideload

scripts/inc.buildtarget.sh
See https://github.com/opengapps/opengapps/issues/799 and https://forum.xda-developers.com/showpost.php?p=81588981&postcount=6495
This can be merged after these PR's:
https://gitlab.opengapps.org/opengapps/all/merge_requests/5 (merged)
https://gitlab.opengapps.org/opengapps/arm/merge_requests/2 (merged)
https://gitlab.opengapps.org/opengapps/arm64/merge_requests/3 (merged)
https://gitlab.opengapps.org/opengapps/x86/merge_requests/2 (merged)
https://gitlab.opengapps.org/opengapps/x86_64/merge_requests/2 (merged)
=> Use separate opengapps-permissions for Q and older OS versions

scripts/inc.buildtarget.sh, scripts/inc.compatibility.sh, scripts/inc.installer.sh
The pixel config files were separated from defaultetc in change
4857790 and removed from gapps zips. Pixels need these
so change it to a core package.
=> Include googlepixelconfig and datatransfertool for pixel devices

scripts/inc.installer.sh
installer: fix OUTFD use when redirected to a log, cleanups:
- append to OUTFD to avoid truncating when redirected to a log file
- use ui_print in backend to simplify error output
installer: support emulator drag-and-drop installs:
- Fixes #813, closes #814
=> Installer OUTFD fixes and emulator support

scripts/inc.installer.sh
* cleaning up $TMP removes busybox and its symlinks, causing
umount to fail with `umount: not found`
* This went unnoticed cause TWRP and older Lineage Recovery
shipped their toolbox in /sbin, which was available at the time
of unmounting.
Lineage Recovery 17.1 however, ships its toybox in /system/bin,
which is unavailable when unmounting because android's system
is mounted at /system at that moment.
=> installer: fix exxit unmounting

scripts/inc.aromadata.sh, scripts/inc.buildtarget.sh, scripts/inc.compatibility.sh
SoundPicker is not a critical component as all ROMs have a Media storage or a file explorer to pick sounds.
Fixes #767.
Changes:
- Moves SoundPicker from core to pico package
- Makes it configurable with tag "SoundPicker"
- Adds it as an option in the AROMA version.
=> SoundPicker: move into PicoGApps, making it removable 

scripts/templates/installer.sh
This is needed so that the installer script can remove stock/aosp  
items on /product and install overlay apk's to /vendor.
=> installer: Support vendor and product dynamic partitions

scripts/inc.buildtarget.sh
`/product` seems to be a better place after all.
Also added `DefaultDialerOverlay` overlay to finally support making Google Dialer the default.
See [this PR](https://gitlab.opengapps.org/opengapps/all/-/merge_requests/11) for the related changes to the overlays.
=> Move overlays to /product, add Google Dialer overlay

scripts/templates/installer.sh
Google released no-gms builds of tvlauncher and tvrecommendations on aosp. Lineage ships these as TVLauncherNoGMS and TVRecommendationsNoGMS.
=> Remove no-gms tvlauncher when installing normal tvlauncher

scripts/inc.compatibility.sh
The gmssetup apk is being included in api 28 and greater opengapps
zips, but google replaced gmssetup with backuprestore in api 28 and
greater, so fix inclusion logic so that gmssetup is not included in api 28+.
=> Fix inclusion of gmssetup

scripts/inc.compatibility.sh
Avoids installing actionsservices twice on Android 10 with super package
=> Add actionsservices to super only on API 28

scripts/build_gapps.sh, scripts/inc.aromadata.sh, scripts/inc.buildhelper.sh, scripts/inc.buildtarget.sh, scripts/inc.compatibility.sh, scripts/inc.packagetarget.sh, scripts/inc.tools.sh, scripts/templates/installer.sh, show_apksignature.sh
- Added: Google Recorder to the `full` variant for SDK28 and up
- Fixed: Chrome and Webview are now properly picked for SDK29
- Fixed: set SELinux context for overlays
- Fixed: added overlays to the cleanup list
- Fixed: repack libs inside of the APK only in cases when there are compresed libs inside (fixes the missing signature issue for most of the cases)
- Fixed: zipalign only APKs with v1 signature from jarsigner
- Added: `apksigner` utility requirement for the APK signature checks
=> Add Google Recorder to `full` variant, various fixes

add_sourceapp.sh, get_speechfiles.sh, report_sources.sh, scripts/build_gapps.sh, scripts/inc.buildhelper.sh, upload_sources.sh
Rather than assume that `$PWD` is also `$TOP`, discover `$TOP` by `cd`ing to the directory containing the script. This assumes that the script is not executed via symlink, or, if it is, that the symlink is in the same directory as the script itself.
Also eliminate the remaining uses of `realpath`.
=> Improve discovery of the `$TOP` directory

scripts/bkup_tail.sh, scripts/templates/installer.sh
- fix remaining instances of /system needing to be changed to $SYS
- fix overlays having context set to tmpfs after restores
- fix some directories having rwxrwxrwx permissions (e.g. srec) after restores
=> Installer and addon.d fixes for consistency through addon.d restores

scripts/templates/installer.sh
The ch_con function was renamed to ch_con_system in a previous commit
but all calls were not renamed, so this change fixes that.
Addresses following errors during zip install:
/tmp/installer.sh: line 1454: ch_con: not found
/tmp/installer.sh: line 2958: ch_con: not found
/tmp/installer.sh: line 2961: ch_con: not found
=> installer: Fix ch_con function calls

scripts/inc.compatibility.sh
Fixes builds for non-ARM64 archs
Closes #866
=> Remove Chrome and Webview for SDK29 for non-ARM64 archs for now

scripts/templates/installer.sh
* As we dont mount /product for devices that are not dynamic
and have a separate partition, on such devices AOSP counterpart
apps in /product end up not being removed, among possibly other
similar issues as well.
* So mount it.
Thanks to @nikhilmenghani for the tip
=> installer: mount /product for non dynamic devices as well

scripts/bkup_tail.sh
* On devices with a separate product partition, addon scripts were
not able to remove AOSP counterpart apps among possibly other
similar issues as well
* So fix it by mounting product before we get started
* While we're at it, mount vendor too since its mounted in the
main installer script
* Thanks to @NikhilMenghani for his input
Fixes https://github.com/opengapps/opengapps/issues/872 for A only devices.
=> addon: handle mounting of {product,vendor} on A only devices

scripts/inc.buildtarget.sh
* This makes OpenGApps tvmini fit on the smallest most relevant build target - fugu (Nexus Player) - our certs have been revoked anyway, so no protected content.
=> tvmini: Remove CastReciever

scripts/inc.compatibility.sh, scripts/inc.installer.sh, scripts/templates/installer.sh
The pixel launcher overlay apk gives exclusive special permissions to
the pixel launcher app for the Recents UI. This causes aosp/stock
launchers to crash. The pixel launcher overlay is only installed
in api28 and newer, so this change adds launcher to the removal list
in api28+ to fix this problem.
=> Add launcherhack to fix pixellauncher overlay issue

scripts/bkup_tail.sh, scripts/templates/installer.sh
* As osm0sis suggested (https://github.com/opengapps/opengapps/pull/879#issuecomment-687478305)
some weird A only devices, seem to report slot as _a.
* So check with ro.build.ab_update instead (as its defined for every A/B device)
* $system_as_root in the installer.sh is unused elsewhere, so drop that too.
Reference:
- https://source.android.com/devices/tech/ota/ab/ab_implement#build-variables
- https://android.googlesource.com/platform/build/+/532fdf4479acb50cdb480e6fdfe24f0698fcd67b%5E%21/
- https://android.googlesource.com/platform/build/+/refs/tags/android-7.1.0_r1/tools/buildinfo.sh#26
- https://android.googlesource.com/platform/build/+/refs/tags/android-10.0.0_r41/tools/buildinfo.sh#28
=> installer/addon: Check A/B partitioning with ro.build.ab_update instead

scripts/inc.compatibility.sh
Fixes missing 8.0 builds for everything non-TV related - there are no SDK26-specific GMS packages, only SDK23 and SDK27+. This caused the builds for SDK26 to fail since July (!).
So, we use SDK23 as the minAPI one.
=> Fix GMS issue for SDK27 and lower

download_sources.sh
Fixes #890.
Changes:
- adds `git lfs pull` after cloning repo to download dependencies from gitlab
=> Add git lfs pull to download_sources.sh

scripts/inc.compatibility.sh
Since we've got a lot of requests to add Android Auto stub package to the `pico` as well, here it is.
Any user will be able to exclude it with the `gearheadstub` keyword in gapps-config file.
=> Move gearheadstub to pico

scripts/templates/installer.sh
Include 'ro.system.product.cpu.abilist' and 'ro.vendor.product.cpu.abilist' in the search.
Set architecture using 'ro.product.cpu.abilist' if it matches 'ro.system.product.cpu.abilist'.
If architecture was not set, try to set it from another prop value.
- If exists, use 'ro.system.product.cpu.abilist'
- If exists, use 'ro.vendor.product.cpu.abilist'
- If exists, use 'ro.odm.product.cpu.abilist'
- Fall back to 'ro.product.cpu.abi' if it still exists.
- Give up and set it to what ever 'ro.product.cpu.abilist' returns.
This should fix the issue when the wrong architecture was being returned.
=> Improve architecture check

scripts/templates/installer.sh
This is where the stock camera lives on LineageOS on a Moto X4 "payton".
=> Add priv-app/MotCamera2 to the removal list

add_sourceapp.sh, get_speechfiles.sh, report_sources.sh, scripts/build_gapps.sh, scripts/inc.buildhelper.sh, scripts/inc.buildtarget.sh, scripts/inc.compatibility.sh, scripts/inc.installer.sh, scripts/inc.sourceshelper.sh, scripts/templates/installer.sh
Comments are welcome.
To add packages, new google certificates need to be added to the opengapps keystore #949 
Go variants are suffixed with "_go" (except super which contains in itself the go packages).
For example 
`bash build_gapps.sh arm 31 pico_go`
=> add Go edition variants

scripts/inc.installer.sh, scripts/templates/installer.sh
- update apex mounting support for Android 11+
- check before mounts, fix persist mount on Virtual A/B
- fix apex mounts on fastboot boot'd TWRP
- support Android 12 .capex (compressed apex) files
- fix some (bad) OEM prop files including entries twice, use last entry like live system
- add useful mount debugging stderr for logs
- don't unmount any existing apex at start of flash
- support AMLogic devices where A-only sets slot=normal
- correct build.prop locations for getprop replacements
- support /metadata mount as a safer alternative to /persist
- refactor mount_all and umount_all
- use OLD_PATH for exceptions where busybox causes conflicts
- abort apex loop mounts early if failing
- work around loop mounts on newer Lineage-based recoveries by changing shell context
=> installer: update mount logic + make comments uniform
